name: Build & Test

on:
  push:
    branches: [ develop ]
    paths:
      - '**.yml'
      - '**.kt'
      - '**.kts'
      - '**.tidy'
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Build
      run: |
        ./gradlew buildPlugin
        ./gradlew verifyPlugin

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: distribution
        path: './build/distributions/idiolect-azure.zip'

  publish-to-beta:
    runs-on: ubuntu-latest
    needs: build
    # Requires approval - https://github.com/OpenASR/idiolect-azure/settings/environments/788279606/edit
    environment: beta
    env:
      INTELLIJ_CHANNEL: beta
      INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
      INTELLIJ_CERTIFICATE_CHAIN: ${{ secrets.INTELLIJ_CERTIFICATE_CHAIN }}
      INTELLIJ_PRIVATE_KEY: ${{ secrets.INTELLIJ_PRIVATE_KEY }}
      INTELLIJ_PRIVATE_KEY_PASSWORD: ${{ secrets.INTELLIJ_PRIVATE_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: distribution
          path: './build/distributions'

      - name: Publish to beta Marketplace
        run: |
          ./gradlew publishPlugin -x buildPlugin -x verifyPlugin

  publish-to-eap:
    runs-on: ubuntu-latest
    needs: build
    # Requires approval - https://github.com/OpenASR/idiolect-azure/settings/environments/788279606/edit
    environment: eap
    env:
      INTELLIJ_CHANNEL: eap
      INTELLIJ_PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
      INTELLIJ_CERTIFICATE_CHAIN: ${{ secrets.INTELLIJ_CERTIFICATE_CHAIN }}
      INTELLIJ_PRIVATE_KEY: ${{ secrets.INTELLIJ_PRIVATE_KEY }}
      INTELLIJ_PRIVATE_KEY_PASSWORD: ${{ secrets.INTELLIJ_PRIVATE_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: distribution
          path: './build/distributions'

      - name: Publish to eap Marketplace
        run: |
          ./gradlew publishPlugin -x buildPlugin -x verifyPlugin
